root@mx-linux:~# ss -n
Netid             State              Recv-Q              Send-Q                                                                Local Address:Port                              Peer Address:Port
u_str             ESTAB              0                   0                                                                @/tmp/.X11-unix/X0 25928                                        * 25927
u_str             ESTAB              0                   0                                                                                 * 198950                                       * 198951
u_str             ESTAB              0                   0                                                                                 * 17771                                        * 17772
u_str             ESTAB              0                   0                                                                                 * 203274                                       * 203273
u_str             ESTAB              0                   0                                                                                 * 196096                                       * 196097
u_str             ESTAB              0                   0                                                                                 * 25932                                        * 25933
u_str             ESTAB              0                   0                                                                                 * 198949                                       * 0
u_str             ESTAB              0                   0                                                                                 * 203273                                       * 203274
u_str             ESTAB              0                   0                                                                                 * 28398                                        * 28399
u_str             ESTAB              0                   0                                                                                 * 24498                                        * 24499
u_str             ESTAB              0                   0                                                                                 * 23651                                        * 0
u_str             ESTAB              0                   0                                                             @/tmp/dbus-8KvTtdeBKi 25933                                        * 25932
u_str             ESTAB              0                   0                                                                                 * 198847                                       * 198848
u_seq             ESTAB              0                   0                                                                                 * 203280                                       * 203279
u_str             ESTAB              0                   0                                                             @/tmp/dbus-8KvTtdeBKi 25245                                        * 25244
u_str             ESTAB              0                   0                                                             @/tmp/dbus-prpJPQJDOC 24502                                        * 24501
u_str             ESTAB              0                   0                                                                                 * 25930                                        * 25931
u_str             ESTAB              0                   0                                                                                 * 199289                                       * 199290
u_str             ESTAB              0                   0                                                                                 * 199276                                       * 199275
u_str             ESTAB              0                   0                                                                                 * 203428                                       * 203429
u_str             ESTAB              0                   0                                                             @/tmp/dbus-prpJPQJDOC 195848                                       * 195847
u_str             ESTAB              0                   0                                                                @/tmp/.X11-unix/X0 24506                                        * 24505
u_str             ESTAB              0                   0                                                                                 * 21583                                        * 0
u_str             ESTAB              0                   0                                                             @/tmp/dbus-prpJPQJDOC 25931                                        * 25930
u_str             ESTAB              0                   0                                                                                 * 198951                                       * 198950
u_str             ESTAB              0                   0                                                   /var/run/dbus/system_bus_socket 20399                                        * 20398
u_str             ESTAB              0                   0                                                                                 * 203282                                       * 203281
u_str             ESTAB              0                   0                                                                                 * 25244                                        * 25245
u_str             ESTAB              0                   0                                                                                 * 24501                                        * 24502
u_str             ESTAB              0                   0                                                                                 * 25927                                        * 25928
u_str             ESTAB              0                   0                                                                                 * 199275                                       * 199276
u_str             ESTAB              0                   0                                                                                 * 203429                                       * 203428
u_str             ESTAB              0                   0                                                                                 * 195847                                       * 195848
u_str             ESTAB              0                   0                                                                @/tmp/.X11-unix/X0 24499                                        * 24498
u_str             ESTAB              0                   0                                                                                 * 21623                                        * 21622
u_str             ESTAB              0                   0                                                                                 * 197409                                       * 197408
u_str             ESTAB              0                   0                                                                                 * 199290                                       * 199289
u_seq             ESTAB              0                   0                                                                                 * 203279                                       * 203280
u_str             ESTAB              0                   0                                                                @/tmp/.X11-unix/X0 28399                                        * 28398
u_str             ESTAB              0                   0                                                                                 * 24505                                        * 24506
u_str             ESTAB              0                   0                                                                                 * 21622                                        * 21623
u_str             ESTAB              0                   0                                                                                 * 197570                                       * 197571
u_str             ESTAB              0                   0                                                                                 * 198848                                       * 198847
u_str             ESTAB              0                   0                                                                                 * 203281                                       * 203282
u_str             ESTAB              0                   0                                                                                 * 196095                                       * 196094
u_str             ESTAB              0                   0                                                                                 * 197582                                       * 197583
u_str             ESTAB              0                   0                                                                                 * 196058                                       * 196059
u_str             ESTAB              0                   0                                                             @/tmp/dbus-prpJPQJDOC 25495                                        * 25494
u_str             ESTAB              0                   0                                                                                 * 24481                                        * 24480
u_str             ESTAB              0                   0                                                                                 * 24013                                        * 24012
u_str             ESTAB              0                   0                                                                                 * 197583                                       * 197582
u_str             ESTAB              0                   0                                                                                 * 196075                                       * 196076
u_str             ESTAB              0                   0                                                              @/tmp/.ICE-unix/4076 24799                                        * 24798
u_str             ESTAB              0                   0                                                                @/tmp/.X11-unix/X0 25302                                        * 25301
u_str             ESTAB              0                   0                                                                                 * 24014                                        * 24015
u_str             ESTAB              0                   0                                                                                 * 20386                                        * 20385
u_str             ESTAB              0                   0                                                                                 * 17772                                        * 17771
u_str             ESTAB              0                   0                                                   /var/run/dbus/system_bus_socket 195977                                       * 195976
u_str             ESTAB              0                   0                                                                @/tmp/.X11-unix/X0 24046                                        * 24045
u_str             ESTAB              0                   0                                                                                 * 24798                                        * 24799
u_seq             ESTAB              0                   0                                                                                 * 197580                                       * 197581
u_str             ESTAB              0                   0                                                                @/tmp/.X11-unix/X0 24422                                        * 24421
u_str             ESTAB              0                   768                                                              @/tmp/.X11-unix/X0 23995                                        * 23994
u_str             ESTAB              0                   0                                                                                 * 195976                                       * 195977
u_str             ESTAB              0                   0                                                                                 * 20530                                        * 20529
u_str             ESTAB              0                   0                                                                                 * 203590                                       * 203591
u_str             ESTAB              0                   0                                                                                 * 24796                                        * 24797
u_str             ESTAB              0                   0                                                              @/tmp/.ICE-unix/4076 25317                                        * 25316
u_str             ESTAB              0                   0                                                                                 * 24421                                        * 24422
u_str             ESTAB              0                   0                                                                                 * 24012                                        * 24013
u_str             ESTAB              0                   0                                                   /var/run/dbus/system_bus_socket 18280                                        * 18279
u_str             ESTAB              0                   0                                                                @/tmp/.X11-unix/X0 195846                                       * 195845
u_str             ESTAB              0                   0                                                                                 * 24045                                        * 24046
u_str             ESTAB              0                   0                                                                                 * 24794                                        * 24795
u_str             ESTAB              0                   0                                                                                 * 197602                                       * 197603
u_str             ESTAB              0                   0                                         /run/user/1000/kded5TcSRNF.1.slave-socket 28650                                        * 28649
u_str             ESTAB              0                   0                                                                                 * 24679                                        * 24680
u_str             ESTAB              0                   0                                                                @/tmp/.X11-unix/X0 196076                                       * 196075
u_str             ESTAB              0                   0                                                                                 * 24057                                        * 24058
u_str             ESTAB              0                   0                                                             @/tmp/dbus-8KvTtdeBKi 24795                                        * 24794
u_str             ESTAB              0                   0                                                                                 * 197217                                       * 197218
u_str             ESTAB              0                   0                                                                                 * 25494                                        * 25495
u_str             ESTAB              0                   0                                                                                 * 24430                                        * 24431
u_str             ESTAB              0                   0                                                                                 * 24063                                        * 24064
u_str             ESTAB              0                   0                                                                                 * 18279                                        * 18280
u_str             ESTAB              0                   0                                                                                 * 197584                                       * 197585
u_str             ESTAB              0                   0                                                                @/tmp/.X11-unix/X0 196059                                       * 196058
u_str             ESTAB              0                   0                                                   /var/run/dbus/system_bus_socket 24790                                        * 24789
u_str             ESTAB              0                   0                                                                                 * 25301                                        * 25302
u_str             ESTAB              0                   0                                                   /var/run/dbus/system_bus_socket 24431                                        * 24430
u_str             ESTAB              0                   0                                                                                 * 20385                                        * 20386
u_str             ESTAB              0                   0                                                                                 * 195845                                       * 195846
u_str             ESTAB              0                   0                                                                                 * 20529                                        * 20530
u_str             ESTAB              0                   0                                                                                 * 203591                                       * 203590
u_str             ESTAB              0                   0                                                              @/tmp/.ICE-unix/4076 24797                                        * 24796
u_str             ESTAB              0                   0                                                                                 * 25316                                        * 25317
u_str             ESTAB              0                   0                                                             @/tmp/dbus-prpJPQJDOC 24678                                        * 24677
u_str             ESTAB              32                  0                                                                                 * 23994                                        * 23995
u_str             ESTAB              0                   0                                                                                 * 25061                                        * 25062
u_str             ESTAB              0                   0                                                             @/tmp/dbus-8KvTtdeBKi 195844                                       * 195843
u_str             ESTAB              0                   0                                                                                 * 20381                                        * 20382
u_str             ESTAB              0                   0                                     /run/user/1000/klauncherHmsjPE.1.slave-socket 29571                                        * 29570
u_str             ESTAB              0                   0                                                                                 * 24934                                        * 24935
u_str             ESTAB              0                   0                                                                                 * 18422                                        * 18423
u_str             ESTAB              0                   0                                                                                 * 25036                                        * 25037
u_str             ESTAB              0                   0                                                                                 * 25222                                        * 25223
u_str             ESTAB              0                   0                                                                                 * 20382                                        * 20381
u_str             ESTAB              0                   0                                                   /var/run/dbus/system_bus_socket 25627                                        * 25626
u_str             ESTAB              0                   0                                                                                 * 25521                                        * 25522
u_str             ESTAB              0                   0                                                                                 * 24835                                        * 24836
u_str             ESTAB              0                   0                                                                                 * 18343                                        * 18344
u_str             ESTAB              0                   0                                                             @/tmp/dbus-8KvTtdeBKi 25037                                        * 25036
u_str             ESTAB              0                   0                                                                                 * 198431                                       * 198432
u_str             ESTAB              0                   0                                                                @/tmp/.X11-unix/X0 25227                                        * 25226
u_str             ESTAB              0                   0                                                                                 * 20379                                        * 20380
u_str             ESTAB              0                   0                                                                                 * 197585                                       * 197584
u_str             ESTAB              0                   0                                                   /var/run/dbus/system_bus_socket 25467                                        * 25466
u_str             ESTAB              0                   0                                                              @/tmp/.ICE-unix/4076 24830                                        * 24829
u_str             ESTAB              0                   0                                                             @/tmp/dbus-prpJPQJDOC 25050                                        * 25049
u_str             ESTAB              0                   0                                                                                 * 198434                                       * 198433
u_str             ESTAB              0                   0                                                                                 * 195843                                       * 195844
u_str             ESTAB              0                   0                                                                                 * 40717                                        * 40718
u_str             ESTAB              0                   0                                                                                 * 25466                                        * 25467
u_str             ESTAB              0                   0                                                             @/tmp/dbus-prpJPQJDOC 24935                                        * 24934
u_str             ESTAB              0                   0                                                                                 * 20383                                        * 20384
u_str             ESTAB              0                   0                                                             @/tmp/dbus-8KvTtdeBKi 25217                                        * 25216
u_str             ESTAB              0                   0                                                                                 * 198433                                       * 198434
u_str             ESTAB              0                   0                                                                                 * 25226                                        * 25227
u_str             ESTAB              0                   0                                                                                 * 20380                                        * 20379
u_str             ESTAB              0                   0                                                                                 * 40696                                        * 40697
u_str             ESTAB              0                   0                                                                                 * 25626                                        * 25627
u_str             ESTAB              0                   0                                                                                 * 24829                                        * 24830
u_str             ESTAB              0                   0                                                   /var/run/dbus/system_bus_socket 25223                                        * 25222
u_str             ESTAB              0                   0                                                   /var/run/dbus/system_bus_socket 20376                                        * 20375
u_str             ESTAB              0                   0                                                             @/tmp/dbus-8KvTtdeBKi 25568                                        * 25567
u_str             ESTAB              0                   0                                                             @/tmp/dbus-8KvTtdeBKi 24836                                        * 24835
u_str             ESTAB              0                   0                                                   /var/run/dbus/system_bus_socket 18423                                        * 18422
u_str             ESTAB              0                   0                                                   /var/run/dbus/system_bus_socket 25062                                        * 25061
u_str             ESTAB              0                   0                                                                                 * 25220                                        * 25221
u_str             ESTAB              0                   0                                                                                 * 20375                                        * 20376
u_str             ESTAB              0                   0                                                                                 * 197603                                       * 197602
u_str             ESTAB              0                   0                                                   /var/run/dbus/system_bus_socket 40697                                        * 40696
u_str             ESTAB              0                   0                                                                                 * 24831                                        * 24832
u_str             ESTAB              0                   0                                                   /var/run/dbus/system_bus_socket 18344                                        * 18343
u_str             ESTAB              0                   0                                                                                 * 25049                                        * 25050
u_str             ESTAB              0                   0                                                                                 * 198432                                       * 198431
u_str             ESTAB              0                   0                                                   /var/run/dbus/system_bus_socket 25221                                        * 25220
u_str             ESTAB              0                   0                                                             @/tmp/dbus-prpJPQJDOC 25464                                        * 25463
u_str             ESTAB              0                   0                                                              @/tmp/.ICE-unix/4076 24832                                        * 24831
u_str             ESTAB              0                   0                                                                                 * 23916                                        * 23917
u_str             ESTAB              0                   0                                                             @/tmp/dbus-prpJPQJDOC 25027                                        * 25026
u_str             ESTAB              0                   0                                                                @/tmp/.X11-unix/X0 24706                                        * 24705
u_str             ESTAB              0                   0                                                                                 * 197408                                       * 197409
u_str             ESTAB              0                   0                                                                                 * 24691                                        * 24692
u_str             ESTAB              0                   0                                                                                 * 17932                                        * 0
u_str             ESTAB              0                   0                                                                                 * 24451                                        * 24452
u_str             ESTAB              0                   0                                                                                 * 23714                                        * 23715
u_str             ESTAB              0                   0                                                                                 * 25026                                        * 25027
u_str             ESTAB              0                   0                                                              @/tmp/.ICE-unix/4076 24711                                        * 24710
u_str             ESTAB              0                   0                                                                                 * 197407                                       * 0
u_str             ESTAB              0                   0                                                                                 * 24699                                        * 24700
u_str             ESTAB              0                   0                                                                @/tmp/.X11-unix/X0 24072                                        * 24071
u_str             ESTAB              0                   0                                                                                 * 24449                                        * 24450
u_str             ESTAB              0                   0                                                                                 * 198111                                       * 198110
u_str             ESTAB              0                   0                                                                @/tmp/.X11-unix/X0 25032                                        * 25031
u_str             ESTAB              0                   0                                                                                 * 24721                                        * 24722
u_str             ESTAB              0                   0                                                                @/tmp/.X11-unix/X0 25285                                        * 25284
u_str             ESTAB              0                   0                                                             @/tmp/dbus-8KvTtdeBKi 24680                                        * 24679
u_str             ESTAB              0                   0                                                                                 * 17937                                        * 0
u_str             ESTAB              0                   0                                                                @/tmp/.X11-unix/X0 24444                                        * 24442
u_str             ESTAB              0                   0                                                   /var/run/dbus/system_bus_socket 18114                                        * 18113
u_str             ESTAB              0                   0                                                                                 * 198109                                       * 0
u_str             ESTAB              0                   0                                                   /var/run/dbus/system_bus_socket 40718                                        * 40717
u_str             ESTAB              0                   0                                                                                 * 24723                                        * 24724
u_str             ESTAB              0                   0                                                             @/tmp/dbus-8KvTtdeBKi 24686                                        * 24685
u_str             ESTAB              0                   0                                                                @/tmp/.X11-unix/X0 24455                                        * 24454
u_str             ESTAB              0                   0                                                                @/tmp/.X11-unix/X0 24058                                        * 24057
u_str             ESTAB              0                   0                                                                                 * 20967                                        * 20968
u_str             ESTAB              0                   0                                                                                 * 198110                                       * 198111
u_str             ESTAB              0                   0                                                              @/tmp/.ICE-unix/4076 24955                                        * 24954
u_str             ESTAB              0                   0                                                                                 * 24710                                        * 24711
u_str             ESTAB              0                   0                                                                                 * 24701                                        * 24702
u_str             ESTAB              0                   0                                                                                 * 24071                                        * 24072
u_str             ESTAB              0                   0                                                             @/tmp/dbus-prpJPQJDOC 24452                                        * 24451
u_str             ESTAB              0                   0                                                                                 * 18113                                        * 18114
u_str             ESTAB              0                   0                                                                                 * 23715                                        * 23714
u_str             ESTAB              0                   0                                                                                 * 216253                                       * 0
u_str             ESTAB              0                   0                                   /run/user/1000/plasmashellkbjDnx.1.slave-socket 25884                                        * 0
u_str             ESTAB              0                   0                                                             @/tmp/dbus-prpJPQJDOC 24722                                        * 24721
u_str             ESTAB              0                   0                                                                                 * 25463                                        * 25464
u_str             ESTAB              0                   0                                                             @/tmp/dbus-prpJPQJDOC 24700                                        * 24699
u_str             ESTAB              0                   0                                                                                 * 17939                                        * 17940
u_str             ESTAB              0                   0                                                                                 * 199523                                       * 199522
u_str             ESTAB              0                   0                                                                                 * 24454                                        * 24455
u_str             ESTAB              0                   0                                /tmp/sddm-auth75124498-711a-4a57-89c1-adcf8390d1b0 23917                                        * 23916
u_str             ESTAB              0                   0                                                                                 * 25031                                        * 25032
u_str             ESTAB              0                   0                                                                                 * 24705                                        * 24706
u_str             ESTAB              0                   0                                                                                 * 28649                                        * 28650
u_str             ESTAB              0                   0                                                                                 * 24685                                        * 24686
u_str             ESTAB              0                   0                                                                                 * 199522                                       * 199523
u_str             ESTAB              0                   0                                                                @/tmp/.X11-unix/X0 24450                                        * 24449
u_str             ESTAB              0                   0                                                                                 * 20384                                        * 20383
u_str             ESTAB              0                   0                                                   /var/run/dbus/system_bus_socket 20968                                        * 20967
u_str             ESTAB              0                   0                                                                                 * 24954                                        * 24955
u_str             ESTAB              0                   0                                                                @/tmp/.X11-unix/X0 24702                                        * 24701
u_str             ESTAB              0                   0                                                                                 * 25284                                        * 25285
u_str             ESTAB              0                   0                                                                @/tmp/.X11-unix/X0 24692                                        * 24691
u_str             ESTAB              0                   0                                                                @/tmp/.X11-unix/X0 24064                                        * 24063
u_seq             ESTAB              0                   0                                                                                 * 197581                                       * 197580
u_str             ESTAB              0                   0                                                                                 * 24442                                        * 24444
u_seq             ESTAB              0                   0                                                                                 * 197402                                       * 197401
u_str             ESTAB              0                   0                                                             @/tmp/dbus-prpJPQJDOC 24826                                        * 24825
u_str             ESTAB              0                   0                                                                                 * 203270                                       * 203269
u_str             ESTAB              0                   0                                                             @/tmp/dbus-8KvTtdeBKi 25522                                        * 25521
u_str             ESTAB              0                   0                                                                                 * 25216                                        * 25217
u_str             ESTAB              0                   0                                                             @/tmp/dbus-prpJPQJDOC 42013                                        * 42012
u_str             ESTAB              0                   0                                                             @/tmp/dbus-fqh5Bn9C58 196101                                       * 196100
u_str             ESTAB              0                   0                                                             @/tmp/dbus-8KvTtdeBKi 24828                                        * 24827
u_str             ESTAB              0                   0                                                                                 * 203272                                       * 203271
u_str             ESTAB              0                   0                                                                                 * 197575                                       * 197574
u_str             ESTAB              0                   0                                                                                 * 196106                                       * 196107
u_str             ESTAB              0                   0                                                                                 * 24808                                        * 24809
u_str             ESTAB              0                   0                                                                                 * 25567                                        * 25568
u_str             ESTAB              0                   0                                                                                 * 197574                                       * 197575
u_str             ESTAB              0                   0                                                                                 * 196100                                       * 196101
u_str             ESTAB              0                   0                                                   /var/run/dbus/system_bus_socket 24809                                        * 24808
u_str             ESTAB              0                   0                                                             @/tmp/dbus-prpJPQJDOC 42035                                        * 42034
u_str             ESTAB              0                   0                                                                @/tmp/.X11-unix/X0 196097                                       * 196096
u_str             ESTAB              0                   0                                                                                 * 24827                                        * 24828
u_str             ESTAB              0                   0                                                                                 * 203271                                       * 203272
u_seq             ESTAB              0                   0                                                                                 * 198089                                       * 0
u_str             ESTAB              0                   0                                                                                 * 197573                                       * 197572
u_str             ESTAB              0                   0                                                             @/tmp/dbus-8KvTtdeBKi 196107                                       * 196106
u_str             ESTAB              0                   0                                                                                 * 24825                                        * 24826
u_str             ESTAB              0                   0                                                                                 * 203269                                       * 203270
u_str             ESTAB              0                   0                                                                                 * 42012                                        * 42013
u_str             ESTAB              0                   0                                                                                 * 199277                                       * 199278
u_str             ESTAB              0                   0                                                                                 * 20398                                        * 20399
u_str             ESTAB              0                   0                                                             @/tmp/dbus-prpJPQJDOC 24805                                        * 24804
u_str             ESTAB              0                   0                                                             @/tmp/dbus-prpJPQJDOC 24477                                        * 24476
u_str             ESTAB              0                   0                                                                                 * 206882                                       * 206883
u_seq             ESTAB              0                   0                                                                                 * 197401                                       * 197402
u_str             ESTAB              0                   0                                                                @/tmp/.X11-unix/X0 24352                                        * 24351
u_str             ESTAB              0                   0                                                                                 * 199279                                       * 199280
u_str             ESTAB              0                   0                                                                                 * 197214                                       * 197215
u_str             ESTAB              0                   0                                                                                 * 24802                                        * 24803
u_str             ESTAB              0                   0                                                                                 * 24476                                        * 24477
u_str             ESTAB              0                   0                                                                                 * 197329                                       * 197330
u_str             ESTAB              0                   0                                                                                 * 24356                                        * 24357
u_str             ESTAB              0                   0                                                   /var/run/dbus/system_bus_socket 20551                                        * 20550
u_str             ESTAB              0                   0                                                   /var/run/dbus/system_bus_socket 17948                                        * 17947
u_seq             ESTAB              0                   0                                                                                 * 199286                                       * 199285
u_str             ESTAB              0                   0                                                             @/tmp/dbus-prpJPQJDOC 24807                                        * 24806
u_str             ESTAB              0                   0                                                                                 * 24473                                        * 24474
u_str             ESTAB              0                   0                                                              @/tmp/.ICE-unix/4076 197223                                       * 197222
u_str             ESTAB              0                   0                                                                                 * 24346                                        * 24345
u_str             ESTAB              0                   0                                                                                 * 20899                                        * 20900
u_str             ESTAB              0                   0                                                                                 * 17980                                        * 17979
u_str             ESTAB              0                   0                                                                                 * 199288                                       * 199287
u_str             ESTAB              0                   0                                                                                 * 24800                                        * 24801
u_str             ESTAB              0                   0                                                                                 * 24478                                        * 24479
u_str             ESTAB              0                   0                                                                                 * 206883                                       * 206882
u_seq             ESTAB              0                   0                                                                                 * 197405                                       * 197404
u_str             ESTAB              0                   0                                                                                 * 197222                                       * 197223
u_seq             ESTAB              0                   0                                                                                 * 199285                                       * 199286
u_str             ESTAB              0                   0                                                                                 * 19815                                        * 19816
u_str             ESTAB              0                   0                                                             @/tmp/dbus-prpJPQJDOC 24803                                        * 24802
u_str             ESTAB              0                   0                                                             @/tmp/dbus-prpJPQJDOC 24474                                        * 24473
u_str             ESTAB              0                   0                                                                                 * 24351                                        * 24352
u_str             ESTAB              0                   0                                                                                 * 20550                                        * 20551
u_str             ESTAB              0                   0                                                                                 * 199280                                       * 199279
u_str             ESTAB              0                   0                                                                @/tmp/.X11-unix/X0 197215                                       * 197214
u_str             ESTAB              0                   0                                                              @/tmp/.ICE-unix/4076 24801                                        * 24800
u_str             ESTAB              0                   0                                                             @/tmp/dbus-prpJPQJDOC 24472                                        * 24471
u_str             ESTAB              0                   0                                                   /var/run/dbus/system_bus_socket 20900                                        * 20899
u_str             ESTAB              0                   0                                                                                 * 199287                                       * 199288
u_str             ESTAB              0                   0                                                                                 * 24806                                        * 24807
u_str             ESTAB              0                   0                                                                                 * 24471                                        * 24472
u_str             ESTAB              0                   0                                                             @/tmp/dbus-prpJPQJDOC 197330                                       * 197329
u_str             ESTAB              0                   0                                                                                 * 24345                                        * 24346
u_str             ESTAB              0                   0                                                                                 * 17979                                        * 17980
u_str             ESTAB              0                   0                                                                                 * 199278                                       * 199277
u_str             ESTAB              0                   0                                                   /var/run/dbus/system_bus_socket 19816                                        * 19815
u_str             ESTAB              0                   0                                                                                 * 24804                                        * 24805
u_str             ESTAB              0                   0                                                   /var/run/dbus/system_bus_socket 24479                                        * 24478
u_seq             ESTAB              0                   0                                                                                 * 197404                                       * 197405
u_str             ESTAB              0                   0                                                             @/tmp/dbus-prpJPQJDOC 197218                                       * 197217
u_str             ESTAB              0                   0                                                                @/tmp/.X11-unix/X0 24015                                        * 24014
u_str             ESTAB              0                   0                                                                                 * 24606                                        * 24607
u_str             ESTAB              0                   0                                                                @/tmp/.X11-unix/X0 24363                                        * 24362
u_str             ESTAB              0                   0                                                                                 * 202165                                       * 202164
u_str             ESTAB              0                   0                                                             @/tmp/dbus-prpJPQJDOC 24676                                        * 24675
u_str             ESTAB              0                   0                                                                                 * 17803                                        * 17804
u_str             ESTAB              0                   0                                                   /var/run/dbus/system_bus_socket 40714                                        * 40713
u_str             ESTAB              0                   0                                                                                 * 24362                                        * 24363
u_str             ESTAB              0                   0                                                                                 * 202163                                       * 0
u_str             ESTAB              0                   0                                                                @/tmp/.X11-unix/X0 24374                                        * 24373
u_str             ESTAB              0                   0                                                   /var/run/dbus/system_bus_socket 17940                                        * 17939
u_str             ESTAB              0                   0                                                                                 * 197624                                       * 197625
u_str             ESTAB              0                   0                                                             @/tmp/dbus-prpJPQJDOC 24607                                        * 24606
u_str             ESTAB              0                   0                                                                                 * 17860                                        * 17861
u_str             ESTAB              0                   0                                                                                 * 40713                                        * 40714
u_str             ESTAB              0                   0                                                                                 * 29570                                        * 29571
u_str             ESTAB              0                   0                                                                                 * 24669                                        * 24670
u_str             ESTAB              0                   0                                                                                 * 17808                                        * 17809
u_str             ESTAB              0                   0                                                                @/tmp/.X11-unix/X0 24592                                        * 24591
u_str             ESTAB              0                   0                                                                                 * 24677                                        * 24678
u_str             ESTAB              0                   0                                                   /var/run/dbus/system_bus_socket 17809                                        * 17808
u_str             ESTAB              0                   0                                                                                 * 24670                                        * 24669
u_str             ESTAB              0                   0                                                                                 * 17804                                        * 17803
u_str             ESTAB              0                   0                                                                                 * 24373                                        * 24374
u_str             ESTAB              0                   0                                                                                 * 17947                                        * 17948
u_str             ESTAB              0                   0                                                                                 * 202164                                       * 202165
u_str             ESTAB              0                   0                                                       /run/user/1000/pulse/native 197625                                       * 197624
u_str             ESTAB              0                   0                                                                                 * 24675                                        * 24676
u_str             ESTAB              0                   0                                                                                 * 24591                                        * 24592
u_str             ESTAB              0                   0                                                   /var/run/dbus/system_bus_socket 17861                                        * 17860
u_str             ESTAB              0                   0                                                                                 * 25511                                        * 25512
u_str             ESTAB              0                   0                                                   /var/run/dbus/system_bus_socket 24949                                        * 24948
u_str             ESTAB              0                   0                                                              @/tmp/.ICE-unix/4076 24539                                        * 24536
u_str             ESTAB              0                   0                                                                                 * 42034                                        * 42035
u_str             ESTAB              0                   0                                                              @/tmp/.ICE-unix/4076 24724                                        * 24723
u_str             ESTAB              0                   0                                                                                 * 24076                                        * 24077
u_str             ESTAB              0                   0                                                                                 * 198421                                       * 198422
u_str             ESTAB              0                   0                                                                                 * 41964                                        * 41965
u_str             ESTAB              0                   0                                                   /var/run/dbus/system_bus_socket 25910                                        * 25909
u_str             ESTAB              0                   0                                                                @/tmp/.X11-unix/X0 24534                                        * 24533
u_str             ESTAB              0                   0                                                                                 * 24782                                        * 24783
u_str             ESTAB              0                   0                                                                                 * 24413                                        * 24414
u_str             ESTAB              0                   768                                                              @/tmp/.X11-unix/X0 20508                                        * 20507
u_seq             ESTAB              0                   0                                                                                 * 203441                                       * 0
u_str             ESTAB              0                   0                                                                                 * 198420                                       * 198419
u_str             ESTAB              0                   0                                                                                 * 197572                                       * 197573
u_str             ESTAB              0                   0                                                                                 * 24524                                        * 24525
u_str             ESTAB              0                   0                                                                @/tmp/.X11-unix/X0 24787                                        * 24786
u_str             ESTAB              0                   0                                                             @/tmp/dbus-prpJPQJDOC 24401                                        * 24400
u_str             ESTAB              32                  0                                                                                 * 20507                                        * 20508
u_str             ESTAB              0                   0                                                                                 * 198423                                       * 198424
u_str             ESTAB              0                   0                                                                                 * 25916                                        * 25917
u_str             ESTAB              0                   0                                                                                 * 24936                                        * 24937
u_str             ESTAB              0                   0                                                                                 * 24580                                        * 24581
u_str             ESTAB              0                   0                                                                                 * 24786                                        * 24787
u_str             ESTAB              0                   0                                                              @/tmp/.ICE-unix/4076 24674                                        * 24589
u_str             ESTAB              0                   0                                                                                 * 20522                                        * 20523
u_seq             ESTAB              0                   0                                                                                 * 198430                                       * 198429
u_str             ESTAB              0                   0                                                                                 * 196094                                       * 196095
u_str             ESTAB              0                   0                                                                                 * 25909                                        * 25910
u_str             ESTAB              0                   0                                                                @/tmp/.X11-unix/X0 24581                                        * 24580
u_str             ESTAB              0                   0                                                                                 * 24789                                        * 24790
u_str             ESTAB              0                   0                                                        /run/user/1000/kdeinit5__0 24414                                        * 24413
u_str             ESTAB              0                   0                                                                @/tmp/.X11-unix/X0 24077                                        * 24076
u_seq             ESTAB              0                   0                                                                                 * 198429                                       * 198430
u_str             ESTAB              0                   0                                                                @/tmp/.X11-unix/X0 41965                                        * 41964
u_str             ESTAB              0                   0                                                       /run/user/1000/pulse/native 25917                                        * 25916
u_str             ESTAB              0                   0                                                                                 * 24536                                        * 24539
u_str             ESTAB              0                   0                                                                                 * 24780                                        * 24781
u_str             ESTAB              0                   0                                                                                 * 24589                                        * 24674
u_str             ESTAB              0                   0                                                                @/tmp/.X11-unix/X0 20523                                        * 20522
u_str             ESTAB              0                   0                                                                                 * 198419                                       * 198420
u_str             ESTAB              0                   0                                                                @/tmp/.X11-unix/X0 25512                                        * 25511
u_str             ESTAB              0                   0                                                                                 * 24948                                        * 24949
u_str             ESTAB              0                   0                                                                @/tmp/.X11-unix/X0 24525                                        * 24524
u_str             ESTAB              0                   0                                                             @/tmp/dbus-prpJPQJDOC 24781                                        * 24780
u_str             ESTAB              0                   0                                                                                 * 24400                                        * 24401
u_str             ESTAB              0                   0                                                                                 * 198422                                       * 198421
u_str             ESTAB              0                   0                                                                                 * 197571                                       * 197570
u_str             ESTAB              0                   0                                                   /var/run/dbus/system_bus_socket 24937                                        * 24936
u_str             ESTAB              0                   0                                                                                 * 24533                                        * 24534
u_str             ESTAB              0                   0                                                                @/tmp/.X11-unix/X0 24783                                        * 24782
u_str             ESTAB              0                   0                                                                                 * 24480                                        * 24481
u_str             ESTAB              0                   0                                                             @/tmp/dbus-prpJPQJDOC 24357                                        * 24356
u_str             ESTAB              0                   0                                                                                 * 198424                                       * 198423
icmp6             UNCONN             0                   0                                                                                 *:58                                           *:*
tcp               ESTAB              0                   0                                                                      192.168.1.99:22                                192.168.1.22:51605
tcp               ESTAB              0                   0                                                                      192.168.1.99:60082                            44.237.239.70:443
tcp               ESTAB              0                   64                                                                     192.168.1.99:22                                192.168.1.22:51636
